// <auto-generated />
namespace BeerMan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _301001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_301001));
        
        string IMigrationMetadata.Id
        {
            get { return "201910300915462_30.10.01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
