// <auto-generated />
namespace BeerMan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _241003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_241003));
        
        string IMigrationMetadata.Id
        {
            get { return "201910241046209_24.10.03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
